<?php

// this file was generated by running " composer dump-env dev"

return array(
'APP_ENV' => 'dev',
'APP_SECRET' => 'b98735634069141a1a37ff416441af8c',
'DATABASE_URL'=>'mysql://root:@127.0.0.1:3306/curiosiquoi?serverVersion=5.7',
'DB_USER' => 'root',
'DB_PASSWORD' => '',
'DB_NAME' => 'curiosiquoi',
'DB_VERSION' => '5.7',
);